/// <summary>
/// 09. SFXs 폴더의 AudioClip 에셋명과 1:1 대응하는 SFX 식별자 Enum.
/// ⚠️ 이 파일은 SfxEnumGenerator 에디터 툴이 자동 생성합니다.
///    직접 수정하지 마세요. (Tools > Sound > Generate ESfxClip Enum)
/// </summary>
public enum ESfxClip
{
    Amb_SYR_Boss,
    Amb_SYR_Machinery1,
    Amb_SYR_Machinery2,
    Amb_SYR_Machinery3,
    Amb_SYR_Mold1,
    Amb_SYR_Mold2,
    Amb_SYR_Scrap1,
    Amb_SYR_Scrap2,
    Amb_SYR_Scrap3,
    Amb_WalkingNPC,
    SE_Energy_CoreOff,
    SE_Energy_CoreOn,
    SE_Energy_Feeding,
    SE_Energy_Switch,
    SE_Energy_Vanishing,
    SE_Gimmick_Moving,
    SE_Gimmick_TurnHarm,
    SE_PC_Damage,
    SE_PC_DashAir,
    SE_PC_DashMold,
    SE_PC_DashPlatform,
    SE_PC_DashScrap,
    SE_PC_Death,
    SE_PC_Heal,
    SE_PC_HitWallMold,
    SE_PC_HitWallPlatform,
    SE_PC_HitWallScrap,
    SE_PC_Hovering,
    SE_PC_LandMold,
    SE_PC_LandPlatform,
    SE_PC_LandScrap,
    SE_PC_WalkingMold,
    SE_PC_WalkingPlatform,
    SE_PC_WalkingScrap,
    SE_SO_HealingObject,
    SE_TB_Crash,
    SE_TB_Jump,
    SE_TB_Land,
    SE_TB_Rushing,
    SE_TB_Shout,
    SE_TB_Walking,
    SUI_Common_Button,
    SUI_Common_Skip,
    SUI_Dialog_Default,
    SUI_Pause_EndPause,
    SUI_Pause_StartPause,
    SUI_Setting_ChangeKey,
    SUI_Setting_ChangeTab,
    SUI_Setting_ChangeVolume,
    SUI_Title_EndProgram,
    SUI_Title_Input,
    SUI_Title_StartGame,
}
